#!/bin/sh
# Not good, needed for fontconfig
export XDG_DATA_HOME=$SNAP/usr/share
# Font Config
export FONTCONFIG_PATH=$SNAP/etc/fonts/config.d
export FONTCONFIG_FILE=$SNAP/etc/fonts/fonts.conf

# downloading the latest launcher

echo "Downloading latest launcher..."

curl "https://github.com/ripe3/os-runes/raw/master/osrs.jar" -L -o $SNAP_USER_COMMON/osrs.jar -s

echo "Starting launcher..."

java -jar $SNAP_USER_COMMON/osrs.jar
