#!/bin/sh
# Not good, needed for fontconfig
export XDG_DATA_HOME=$SNAP/usr/share
# Font Config
export FONTCONFIG_PATH=$SNAP/etc/fonts/config.d
export FONTCONFIG_FILE=$SNAP/etc/fonts/fonts.conf

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$SNAP/usr/lib/$ARCH/pulseaudio

# downloading the latest launcher

echo "Downloading latest launcher..."

curl "https://github.com/ripe3/os-runes/releases/download/0/osrs.jar" -L -s -o $SNAP_USER_COMMON/osrs.jar 

echo "Starting..."

java -jar $SNAP_USER_COMMON/osrs.jar "$@"
