#!/bin/sh
# Not good, needed for fontconfig
export XDG_DATA_HOME=$SNAP/usr/share
# Font Config
export FONTCONFIG_PATH=$SNAP/etc/fonts/config.d
export FONTCONFIG_FILE=$SNAP/etc/fonts/fonts.conf

if [ "$SNAP_ARCH" = "amd64" ]; then
  ARCH="x86_64-linux-gnu"
elif [ "$SNAP_ARCH" = "armhf" ]; then
  ARCH="arm-linux-gnueabihf"
elif [ "$SNAP_ARCH" = "arm64" ]; then
  ARCH="aarch64-linux-gnu"
elif [ "$SNAP_ARCH" = "ppc64el" ]; then
  ARCH="powerpc64le-linux-gnu"
else
  ARCH="$SNAP_ARCH-linux-gnu"
fi

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$SNAP/usr/lib/$ARCH/pulseaudio
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$SNAP/lib/$ARCH

export PULSE_RUNTIME_PATH=/var/run/pulse
export PULSE_SYSTEM=1

# downloading the latest launcher

echo "Downloading latest launcher..."

curl "https://github.com/ripe3/os-runes/releases/download/0/osrs.jar" -L -s -o $SNAP_USER_COMMON/osrs.jar 

echo "Starting..."

java -jar $SNAP_USER_COMMON/osrs.jar "$@"
