name: os-runes
base: core18
version: '0.3'
summary: Launcher for OS Runescape
description: |
  This snap allows you to download and play Old School Runescape in your
  Linux distro.

grade: stable
confinement: strict
icon: gui/os-runes.png

architectures:
  - build-on: amd64
  - build-on: i386

apps:
  os-runes:
    command: sh $SNAP/run
    desktop: gui/os-runes.desktop
    plugs: 
      - opengl
      - pulseaudio
      - desktop
      - desktop-legacy
      - network
      - x11
    environment: 
      JAVA_HOME: $SNAP/usr/lib/jvm/default-java
      PATH: $JAVA_HOME/bin:$PATH

parts:
  os-runes:
    source: ./
    plugin: dump
    build-packages:
      - ca-certificates
      - ca-certificates-java
      - openjdk-8-jre-headless
    stage-packages:
      - libgl1-mesa-dri
      - libpulse0
      - yad
      - curl
      - libxext6
      - libxrender1
      - libxtst6
      - libxi6
      - libswt-gtk-3-java
      - x11-xserver-utils
      - openjdk-8-jre-headless
      - p7zip-full
