name: os-runes
base: core18
version: '0.2'
summary: Launcher for OS Runescape
description: |
  This snap allows you to download and play Old School Runescape in your
  Linux distro.

grade: stable
confinement: strict
icon: gui/os-runes.png

architectures:
  - build-on: amd64
  - build-on: i386

apps:
  os-runes:
    command: sh $SNAP/run
    desktop: gui/os-runes.desktop
    plugs: 
      - desktop
      - desktop-legacy
      - network
      - pulseaudio
      - opengl
      - x11
      - alsa
    environment: 
      JAVA_HOME: $SNAP/usr/lib/jvm/default-java
      PATH: $JAVA_HOME/bin:$PATH

parts:
  os-runes:
    source: ./
    plugin: dump
    stage-packages:
      - default-jre
      - wget
      - curl
      - p7zip-full
      - gstreamer1.0-pulseaudio
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-libav
      - libgstreamer-plugins-base1.0-0
      - libgstreamer-plugins-good1.0-0
      - libpulse0
      - libflac8
      - libogg0
      - libopus0
      - liborc-0.4-0
      - libspeex1
      - libtheora0
      - libvorbis0a
      - libvpx3
      - libwavpack1
      - libmp3lame0
