name: os-runes
base: core18
version: '0.3'
summary: Launcher for OS Runescape
description: |
  This snap allows you to download and play Old School Runescape in your
  Linux distro.

grade: stable
confinement: strict
icon: gui/os-runes.png

architectures:
  - build-on: amd64
  - build-on: i386

apps:
  os-runes:
    command: sh $SNAP/run
    desktop: gui/os-runes.desktop
    plugs: 
      - desktop
      - desktop-legacy
      - network
      - pulseaudio
      - opengl
      - x11
      - alsa
    environment: 
      JAVA_HOME: $SNAP/usr/lib/jvm/java-1.8.0-openjdk-$SNAP_ARCH
      PATH: $JAVA_HOME/bin:$PATH

parts:
  os-runes:
    source: ./
    plugin: dump
    build-packages:
      - openjdk-8-jre
      - wget
      - curl
      - p7zip-full  
      - libpulse0  
    stage-packages:
      - openjdk-8-jre
      - wget
      - curl
      - p7zip-full
      - libpulse0 
      
